CREATE TABLE IF NOT EXISTS "players_data_end" (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "Nacionalidad" TEXT,
    "Nombre" TEXT,
    "Especialidad" TEXT,
    "Lesiones " REAL,
    "Amonestaciones" REAL,
    "Edad" INTEGER,
    "Días" INTEGER,
    "TSI" INTEGER,
    "Salario" INTEGER,
    "Semanas en el club" INTEGER,
    "Experiencia" INTEGER,
    "Liderazgo" INTEGER,
    "Forma" INTEGER,
    "Resistencia" INTEGER,
    "Portería" INTEGER,
    "Defensa" INTEGER,
    "Jugadas" INTEGER,
    "Lateral" INTEGER,
    "Pases" INTEGER,
    "Anotación" INTEGER,
    "Balón parado" INTEGER,
    "Límite" TEXT,
    "Máxima oferta" TEXT,
    "Precio_venta" INTEGER,
    "Temporada_hat_venta" TEXT,
    "link" TEXT
)