CREATE TABLE IF NOT EXISTS "players" (
    "Id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "index" INTEGER,
    "Unnamed: 0" INTEGER,
    "Nacionalidad" TEXT,
    "Nombre" TEXT,
    "Especialidad" TEXT,
    "Lesiones " REAL,
    "Amonestaciones" REAL,
    "Edad" INTEGER,
    "Días" INTEGER,
    "TSI" INTEGER,
    "Salario" INTEGER,
    "Semanas en el club" INTEGER,
    "Experiencia" INTEGER,
    "Liderazgo" INTEGER,
    "Forma" INTEGER,
    "Resistencia" INTEGER,
    "Portería" INTEGER,
    "Defensa" INTEGER,
    "Jugadas" INTEGER,
    "Lateral " INTEGER,
    "Pases" INTEGER,
    "Anotación" INTEGER,
    "Balón parado" INTEGER,
    "Límite" TEXT,
    "Máxima oferta" TEXT,
    "Ofrecer" INTEGER,
    "Unnamed: 24" REAL,
    "link" TEXT,
    "Precio_venta" INTEGER,
	"Fecha_hat_venta"	TEXT
)